const USERS = 'USERS';
const USER_SETTINGS = 'USER_SETTINGS';
const PROJECT_ADD = 'PROJECT_ADD';
const SCHEDULER_ADD = 'SCHEDULER_ADD';
const PROJECT_SETTINGS = 'PROJECT_SETTINGS';
const SCHEDULER_SETTINGS = 'SCHEDULER_SETTINGS';

export default {
  USERS,
  USER_SETTINGS,
  PROJECT_ADD,
  SCHEDULER_ADD,
  PROJECT_SETTINGS,
  SCHEDULER_SETTINGS,
};
